services:
  zerotier:
    image: zyclonite/zerotier:router
    container_name: zerotier-one
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    restart: unless-stopped
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
    environment:
      - TZ=Etc/UTC
      - PUID=998
      - PGID=100
      - ZEROTIER_ONE_LOCAL_PHYS=eth0
      - ZEROTIER_ONE_USE_IPTABLES_NFT=false
      - ZEROTIER_ONE_GATEWAY_MODE=both
      - ZEROTIER_ONE_NETWORK_IDS=fada62b015740bd1
